version: '3'
services:
  hyperf-skeleton:
    container_name: hyperf-admin
    image: hyperf/hyperf:8.1-alpine-v3.18-swoole
    build:
      context: .
    volumes:
      - ./:/opt/www
    ports:
      - 9501:9501
    environment:
      - APP_ENV=prod
      - SCAN_CACHEABLE=false

networks:
  default:
    name: hyperf-admin