version: '3'
services:
  hyperf-skeleton:
    network_mode: host
    container_name: hyperf-admin
    image: hyperf/hyperf:8.1-alpine-v3.18-swoole
    build:
      context: .
    volumes:
      - "./:${DOCKER_PROJECT_PATH}"
#    ports:
#      - "${HTTP_PORT}:${HTTP_PORT}"
    environment:
      - APP_ENV=prod
      - SCAN_CACHEABLE=false
      - TZ=Asia/Shanghai
    command:
      - /bin/bash
      - -c
      - |
        chmod +x ${DOCKER_PROJECT_PATH}/sh.d/*
        "${DOCKER_PROJECT_PATH}/sh.d/start-server.sh"